utf8_codec: Move character increment inline, better error checking

diff --git a/scripts/utf8_codec/utf8decode b/scripts/utf8_codec/utf8decode
--- a/scripts/utf8_codec/utf8decode
+++ b/scripts/utf8_codec/utf8decode
@@ -4,10 +4,25 @@
 #              the decoded UTF-8 version (one per line).
 #
 
+# Check parameter is valid hex
+# Params:
+#   $1: hex value to check
+__utf8decode_isnib() {
+	case $1 in
+		[0-9A-Fa-f][0-9A-Fa-f])
+			return 0
+			;;
+		*)
+			echo >&2 "Invalid encoding: $1 is not hex"
+			return 1
+	esac
+}
+
 # Check a nibble starts with 0b >>10<< 00 0000
 # Params:
 #   val: hex value to check
 __utf8decode_checknib() {
+	__utf8decode_isnib "$1" || return
 	local -i val=16#$1
 
 	# if/else seems to be a tad faster than default fail
@@ -23,54 +38,49 @@ __utf8decode_checknib() {
 # Params:
 #   var: Value to decode
 utf8decode() {
-	local var=$1 res='' char chr i tmp
+	local var=$1 res='' char tmp
+	local -i chr i
 
-	for ((i=0; i<${#var}; i++)); do
-		char=${var:$i:1}
+	for ((i=0; i<${#var};)); do
+		char=${var:i++:1}
 		if [ "$char" = _ ]; then
-			((++i))
-			tmp=${var:$i:2}
+			# Get first byte
+			tmp=${var:i+=2,i-2:2}
+			__utf8decode_isnib "$tmp" || return 1
 			char="\\x$tmp"
 			chr=16#$tmp
-			((++i))
 			if ((chr & 1 << 7)); then
 				if ((chr & 1 << 6)); then
-					((++i))
-					tmp=${var:$i:2}
-					char+="\\x$tmp"
+					tmp=${var:i+=2,i-2:2}
 					if ! __utf8decode_checknib "$tmp"; then
-						echo >&2 "Invalid encoding"
+						echo >&2 "Invalid encoding: 0x$tmp"
 						return 1
 					fi
-					((++i))
+					char+="\\x$tmp"
 					if ((chr & 1 << 5)); then
-						((++i))
-						tmp=${var:$i:2}
-						char+="\\x$tmp"
+						tmp=${var:i+=2,i-2:2}
 						if ! __utf8decode_checknib "$tmp"; then
-							echo >&2 "Invalid encoding"
+							echo >&2 "Invalid encoding: 0x$tmp"
 							return 1
 						fi
-						((++i))
+						char+="\\x$tmp"
 						if ((chr & 1 << 4)); then
-							((++i))
-							tmp=${var:$i:2}
-							char+="\\x$tmp"
+							tmp=${var:i+=2,i-2:2}
 							if ! __utf8decode_checknib "$tmp"; then
-								echo >&2 "Invalid encoding"
+								echo >&2 "Invalid encoding: 0x$tmp"
 								return 1
 							fi
-							((++i))
+							char+="\\x$tmp"
 							if ((chr & 1 << 3)); then
 								# Prefix cannot have more that 4 1's (0b1111 1000)
-								echo >&2 "Invalid encoding"
+								echo >&2 "Invalid encoding: 0x$tmp"
 								return 1
 							fi
 						fi
 					fi
 				else
 					# Prefix cannot start with 0b1000 0000
-					echo >&2 "Invalid encoding"
+					echo >&2 "Invalid encoding: 0x$tmp"
 					return 1
 				fi
 			fi
